### ISSUE TITLE
License

### ISSUE THREAD

**Issue by claudiv** [maxhollmann/lium-diarization-editor#1]
Hi Max,

Thank you very much for publishing this awesome tool :-). 
I was wondering whether I could use it for my project, I would really appreciate it. Since you haven't added an open source license, I am not sure if I am allowed to?

Best wishes,
Claudia

**Comment by maxhollmann** [comment]
Hi Claudia,

Use it as you like, I'll add a license in a minute.

Cheers,
Max

**Comment by claudiv** [comment]
Super, vielen Dank :)
